Adding and deleting bikes
io2-2021-wed-brodka/A_Admin pull request #17
Opened 2021-04-24 09:23 UTC by jankupis

2021-04-24 16:09 UTC, chlebnymaciej reviewed
please apply those changes

2021-04-24 16:09 UTC, chlebnymaciej commented on src/components/AddBikeDialog.tsx
> +  const [open, setOpen] = React.useState(false);
please add type

2021-04-24 16:09 UTC, chlebnymaciej commented on src/components/AddBikeDialog.tsx
> +            stations.map((station, _) =>
just (station) will work

2021-04-25 10:37 UTC, jankupis commented on src/components/AddBikeDialog.tsx
> +  const [open, setOpen] = React.useState(false);
Done

2021-04-25 10:37 UTC, jankupis commented on src/components/AddBikeDialog.tsx
> +            stations.map((station, _) =>
Done

2021-04-25 12:30 UTC, ArturChmura requested changes

2021-04-25 12:30 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +      setStations((res.data || []).map(x => x));
what is 'map' for?

2021-04-25 12:30 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +          id="demo-simple-select"
change to proper values

2021-04-25 12:30 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +          prev = [...prev, response.data] : prev
response.data will always return true, because you are checking it in elseif above

2021-04-25 12:30 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +          prev = [...prev, response.data] : prev
`prev = [...prev, response.data]` is wrong. Make it `[...prev, response.data]`.

2021-04-25 12:51 UTC, ArturChmura requested changes

2021-04-25 12:51 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +        )
```suggestion
        const data = response.data;
        props.setBikes(prev => [...prev, data])
```

2021-04-25 12:52 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +          prev = [...prev, response.data] : prev
look at my suggestion below

2021-04-25 12:53 UTC, ArturChmura commented on src/components/AddBikeDialog.tsx
> +      setStations((res.data || []).map(x => x));
```suggestion
      setStations(res.data || []);
```

2021-04-25 16:52 UTC, jankupis commented
Applied all suggestions, thanks

2021-04-25 18:59 UTC, ArturChmura approved these changes
Nicely done

2021-04-25 19:08 UTC, merged